//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class reduktorSeri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reduktorSeri()
        {
            this.seriGovdeTipEslesme = new HashSet<seriGovdeTipEslesme>();
        }
    
        public int id { get; set; }
        public string seriAdi { get; set; }
        public Nullable<int> timestampId { get; set; }
    
        public virtual timestamp timestamp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seriGovdeTipEslesme> seriGovdeTipEslesme { get; set; }
    }
}
