//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class reduktor
    {
        public int id { get; set; }
        public Nullable<int> serigovdeTipEsId { get; set; }
        public string reduktorAdi { get; set; }
        public Nullable<double> motorGucu { get; set; }
        public Nullable<double> frekans { get; set; }
        public Nullable<double> cikisDevri { get; set; }
        public Nullable<double> cikisMomenti { get; set; }
        public Nullable<double> servisFaktoru { get; set; }
        public Nullable<int> timestampId { get; set; }
    
        public virtual seriGovdeTipEslesme seriGovdeTipEslesme { get; set; }
        public virtual timestamp timestamp { get; set; }
    }
}
